<hr style="border:5px solid #108999"> </hr>

# Python Variables and Types of Data <hr style="border:4.5px solid #108999"> </hr>

## Variables

Create a variable with name "x" and a value of 10. Execute.

In [1]:
x = 10

Tell the computer to show you the value of that variable.

In [2]:
print(x)

10


Can you think of a second way to obtain the same result? 

In [3]:
print(10)

10


On the same line, create four new variables: a,b,c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [4]:
a, b, c ,d = [10, 20 ,30, 40]

Tell the computer to show you the value corresponding to the variable "b".

In [5]:
print(b)

20


Do the same for "d".

In [6]:
print(d)

40


## Numbers and Boolean Values

Create a variable equal to "True".

In [9]:
t = True

Check its type.

In [10]:
type(t)

bool

Create a variable equal to 99.

In [11]:
num = 99

Check its type.

In [12]:
type(num)

int

Check the type of the value 0.99. 

In [13]:
type(0.99)

float

Turn 99 into a *float*.

In [14]:
float(num)

99.0

In [15]:
float(99)

99.0

Turn 0.99 into an integer. What value did you get?

In [16]:
int(0.99)

0

In [17]:
int(num)

99

## Strings

Assign the value of 100 to the variable "m".

In [18]:
m = 100

With the help of the variable "m", write one line of code where the output after executuion would be *100 days*.

*Hint:* *You could provide four answers to this question!*

In [20]:
print(str(m) + " days")

100 days


In [21]:
print(f"{m} days")

100 days


Produce an output equal to *It's cool, isn't it?*

In [22]:
"Don't be shy"

"Don't be shy"

Fix the string below.

In [ ]:
'Don't be shy

Produce an output equal to *Click "OK"*.

In [23]:
print('Click "OK".')

Click "OK".


Include a plus sign in your line of code to produce *'Big Houses'*.

In [26]:
print('Click "OK"' + ' Big Houses')

Click "OK" Big Houses


Include a trailing comma in your line of code to produce *Big Houses*.

In [27]:
print('Click "OK"', ' Big Houses')

Click "OK"  Big Houses


<hr style="border:5px solid #108999"> </hr>

# Basic Python Syntax <hr style="border:4.5px solid #108999"> </hr>

## Arithmetic operators

Combine 15 and 23.

In [28]:
print(15 + 23)

38


Subtract 50 from 26.

In [29]:
print(50 - 26)

24


Divide 20 by 4.

In [30]:
print(20 / 4)

5.0


Divide 22 by 4.

In [31]:
print(22 / 4)

5.5


Obtain the remainder of the division of 22 by 4.

In [32]:
print(22 % 4)

2


Divide the float 22 by 4.

In [33]:
print(float(22) / 4)

5.5


In [34]:
print(6 * 8)

48


Multiply 6 by 8.

In [35]:
print(15**2)

225


Raise 15 to the power of 2.

## The double-equality sign

Demonstrate that 100 is not equal to 98.

In [36]:
print(100 == 98)

False


## Reassign Values

Assign the value of 14 to a variable p.

In [37]:
p = 14

Calculate p + 10.

In [38]:
int(p) + 10

24

Now, assign 30 to the variable p.

In [39]:
p = 30

Calculate p + 10.

In [40]:
print(int(p) + 10)

40


Observe how the value of p is always the last one you have assigned.

## Line Continuation

Add a backslash in the code below, so it is a one-line code. Observe the change in the result.

In [41]:
15 + 31 \
- 26

20

## Indexing Elements

Extract the letter 'B' from "Bingo!".

In [42]:
word = "Bingo"
print(word[0])

B


Extract the letter "u" from "Constitution".

In [43]:
word2 = "Constitution"
print(word2[7])

u


In [44]:
print(word2[-5])

u


In [45]:
if 'u' in word2:
    print('u')

u


In [46]:
x = "Joshua"

In [47]:
x

'Joshua'

## Structure Your Code with Indentation

Use indentation properly to print the result of the function with an argument of 3.

In [51]:
def ten(x):
    x = 10
    return x
    
print(ten(3))

10


<hr style="border:5px solid #108999"> </hr>

# Operators <hr style="border:4.5px solid #108999"> </hr>

## Comparison Operators

Verify that 25 is smaller than 30. 

In [53]:
print(25 < 30)

True


Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3. 

In [54]:
print((5 * 3) <= (5**3))

True


Verify that 100 is equal to 10 square.

In [55]:
print(100 == (10**2))

True


Verify that 53 is not equal to 46.

In [56]:
print(53 != 46)

True


## Logical and Identity Operators

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Check whether the following code is True or False.

False or not True and not False 

In [77]:
False or not True and not False

False

True and not False and True or not False

In [78]:
True and not False and True or not False

True

True or False and False

In [79]:
True or False and False

True

False and True or False

In [81]:
# False and True or False
3 != 3 and 3 == 3 or 5 != 5


False

Using an identity operator, verify that 10 is not the same as 12.

In [59]:
10 != 12

True

##### Using an identity operator, verify that 50 is the same as 50.

In [60]:
50 == 50

True

<hr style="border:5px solid #108999"> </hr>

# Conditional Statements <hr style="border:4.5px solid #108999"> </hr>

## Introduction to the IF statement

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.

In [61]:
if 5 > 2:
    print('the condition has been satisfied!')
else:
    print('the condition has not been satisified!')

the condition has been satisfied!


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 or y is less than or equal to 13. 
Change the values assigned to x and y and re-run the cell to verify your code still works.

In [63]:
x = 10
y = 25

print("Both conditions are correct" if x > 3 and y > 13 \
      else "at least one is false" if x <= 3 or y <= 13 else "print nothing")

Both conditions are correct


## Add an ELSE Statement

Let x represent the number of orders received during a certain day. 
Assign 102 to x. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise. Change x to 97 to verify your code works properly.

In [65]:
x = 97
print("A busy day" if x > 100 else "a calm day")

a calm day


## Else if, for Brief - ELIF

Assign 200 to x.
Create the following piece of code:
If x > 200, print out "Big"; 
If x > 100 and x <= 200, print out "Average"; 
and If x <= 100, print out "Small".
Use the If, Elif, and Else keywords in your code.

In [70]:
x = 500

if x > 200:
    print("Big")
elif x > 100 and x <= 200:
    print("Average")
elif x <= 100:
    print("Small")
else:
    print(" ")

Big


Change the initial value of x to see how your output will vary.

******

Keep the first two conditions of the previous code. Add a new ELIF statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0. 
Let x carry the value of 50 and then of -50 to check if your code is correct.

In [72]:
x = -50

if x > 200:
    print("Big")
elif x > 100 and x <= 200:
    print("Average")
elif x >= 0 and x <= 100:
    print("Small")
else:
    print("Negative")

Negative


<hr style="border:5px solid #108999"> </hr>

# Functions <hr style="border:4.5px solid #108999"> </hr>

## Creating a Function with a Parameter

Define a function that returns a value equal to its argument multiplied by 2.

In [73]:
x = lambda a : a * 2
print(x(10))

20


Define a funciton that returns a float value equal to its argument divided by 2.

In [75]:
x = lambda a : a * 2
print(float(x(5)))

10.0


## Another Way to Define a Function

Define a function that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called "result", in the body of the Function. 
Call the function with some argument to verify it works properly.

*Hint: Your knowledge about stating multiple elements on a line can be of great help in solving this exercise!*

In [76]:
result = lambda x : x ** 2
print(f"raised to the power of 2: {result(10)}")

raised to the power of 2: 100


## Using a Function in Another Function

Define a function that adds 5 to the parameter. Then, define another function that will multiply the newly obtained number by 3.
Verify your code was correct by calling the second function with an argument of 5. 
Was your output equal to 30?

In [84]:
add = lambda x : x + 5
multiply = lambda y : y * 3

print(add(5))
print(multiply(add(5)))


10
30


## Combining Conditional Statements and Functions

Define a function, called **compare_the_two()**, with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [92]:
def compare(a, b):
    if a > b:
        return "greater"
    elif b > a:
        return "less"
    else:
        return "equal"

print(compare(50, 20))
print(compare(10, 15))
print(compare(5, 5))

greater
less
equal


## Notable Built-In Functions in Python

Obtain the maximum number among the values 25, 65, 890, and 15.

In [93]:
max(25, 65, 890, 15)

890

Obtain the minimum number among the values 25, 65, 890, and 15.

In [94]:
min(25, 65, 890, 15)

15

Find the absolute value of -100

In [95]:
abs(-100)

100

Round the value of 55.5. Did you obtain 56.0?

In [96]:
round(55.5)

56

Round 35.56789 to the third digit.

In [97]:
round(35.56789)

36

Find the sum of all elements in the provided list, called "Numbers".

In [98]:
Numbers = [1, 5, 64, 24.5]

In [99]:
sum(Numbers)

94.5

Use a built-in function to raise 10 to the power of 3.

In [102]:
pow(10, 3)

1000

How many characters are there in the word "Elephant"?

In [103]:
len("Elephant")

8

Create a function, called "distance_from_zero", that returns the absolute value of a provided single argument and prints a statement "Not Possible" if the argument provided is not a number.
Call the funtion with the values of -10 and "cat" to verify it works correctly.

In [110]:
def distance_from_zero(x):
    if type(x) == int or type(x) == float:
        return abs(x)
    else:
        return "Not possible"
    
print(distance_from_zero(10))




10


In [111]:
print(distance_from_zero("cat"))

Not possible


In [112]:
print(distance_from_zero(-10))

10


<hr style="border:5px solid #108999"> </hr>

# Sequences <hr style="border:4.5px solid #108999"> </hr>

## Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [113]:
nums = [10, 25, 40, 50]

Print the element at index 2 from the list.

In [114]:
nums[2]

40

Print the 0th element.

In [115]:
print(nums[0])

10


Print the third-to-last element using a minus sign in the brackets.

In [116]:
print(nums[-3])

25


Substitute the number 10 with the number 15.

In [118]:
nums[0] = 15
print(nums)

[15, 25, 40, 50]


Delete the number 25 from the Numbers list.

In [120]:
del(nums[1])
print(nums)

[15, 50]


## Help Yourself with Methods

Append the number 100 to the Numbers list. 

In [122]:
Numbers = [15, 40, 50]

In [123]:
Numbers.append(100)
print(Numbers)

[15, 40, 50, 100]


With the help of the "extend method", add the numbers 115 an 140 to the list. 

In [126]:
nums = [115, 140]
Numbers.extend(nums)
print(Numbers)

[15, 40, 50, 100, 115, 140]


Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [127]:
print(f"The fourth element of the Numbers list is: {Numbers[4]}")

The fourth element of the Numbers list is: 115


How many elements are there in the Numbers list?

In [128]:
len(Numbers)

6

## List Slicing

In [130]:
Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [132]:
Numbers[3:5]

[100, 115]

Using slicing, extract the first four elements from the list.

In [134]:
print(Numbers)
print(Numbers[0:4])

[15, 40, 50, 100, 115, 140]
[15, 40, 50, 100]


Using slicing, extract all the elements from the list from the 3rd position onwards.

In [135]:
print(Numbers[3:])

[100, 115, 140]


Using slicing, extract the last 4 elements from the list.

In [137]:
print(Numbers[-4:])

[50, 100, 115, 140]


Which is the position of the value 15?

In [139]:
print(Numbers.index(15))

0


Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists. 

In [141]:
Two_Numbers = [1, 2]
All_Numbers = Numbers + Two_Numbers
print(All_Numbers)

[15, 40, 50, 100, 115, 140, 1, 2]


Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [147]:
sorted(Numbers)

[15, 40, 50, 100, 115, 140]

In [149]:
Numbers.sort(reverse=False)
Numbers.sort(reverse=True)
Numbers


[140, 115, 100, 50, 40, 15]

## Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford". 

In [150]:
Cars = ("BMW", "Dodge", "Ford")

Access the second element of this tuple.

In [152]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [153]:
name, age = 'Peter,24'


ValueError: too many values to unpack (expected 2)

In [155]:
name, age = 'Peter, 24'.split(',')

print(name)
print(age)

Peter
 24


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle.
Call the function with arguments 2 and 10 to verify it worked correctly.

In [156]:
def rect(val1, val2):
    area = val1 * val2
    perimeter = 2 * (val1 + val2)
    return area, perimeter

print(f"Area and Perimeter: {rect(2, 10)}")

Area and Perimeter: (20, 24)


## Dictionaries

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

This is the menu of a close-by restaurant:

In [158]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [160]:
Menu['meal_2']

'Fries'

Add a new meal - "Soup".

In [164]:
Menu['meal_5'] =  'Soup'
print(Menu)

{'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Hamburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup'}


Replace the Hamburger with a Cheeseburger.

In [165]:
Menu['meal_3'] = 'Cheeseburger'
print(Menu)

{'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Cheeseburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup'}


Attach the Desserts list in the form of a sixth meal.

In [166]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [168]:
Menu['meal_6'] = Dessert
print(Menu)

{'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Cheeseburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup', 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}


In [180]:
People = {'name_1': 'John', 'name_2': 'Mary', 'name_3': 'Vick'}

print(People['name_1'])
print(People['name_2'])
print(People['name_3'])

People['name_1'] = 'Rob'
People

People['name_4'] = 'Robert'
People['name_5'] = 'Cindy'

People


John
Mary
Vick


{'name_1': 'Rob',
 'name_2': 'Mary',
 'name_3': 'Vick',
 'name_4': 'Robert',
 'name_5': 'Cindy'}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars):
10, 5, 8, 12, 5. 
Start by *Price_list = {}*.

In [188]:
Menu_Prices = {}
Menu_Prices[Menu['meal_1']] = 10
Menu_Prices[Menu['meal_2']] = 5
Menu_Prices[Menu['meal_3']] = 8
Menu_Prices[Menu['meal_4']] = 12
Menu_Prices[Menu['meal_5']] = 5

Menu_Prices

{'Spaghetti': 10, 'Fries': 5, 'Cheeseburger': 8, 'Lasagna': 12, 'Soup': 5}

Use the *.get()* method to check the price of the Spaghetti.

In [189]:
Menu_Prices.get('Spaghetti')

10

<hr style="border:5px solid #108999"> </hr>

# Iteration <hr style="border:4.5px solid #108999"> </hr>

## For Loops

Create a For loop that prints every digit on a new line.

In [191]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [192]:
for d in digits:
    print(d)

0
1
2
3
4
5
6
7
8
9


Adjust the code, so the digits are all printed on the same line.

In [195]:
for d in digits:
    print(d, end=" ")

0 1 2 3 4 5 6 7 8 9 

## While Loops and Incrementing

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a while loop that will print all odd numbers from 0 to 30 on the same row. 
<br />
*Hint: There are two ways in which you can create the odd values!*

In [196]:
x = 1
while x <= 30:
    print(x, end=" ")
    x += 2

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

## Create Lists with the range() Function

Use the range() function to create a list with all numbers from 1 to 10.

In [200]:
list(range(1, 11))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Use the range() function to create a list with all numbers from 0 to 19.

In [201]:
list(range(0, 20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Use the range function to create a list with all even numbers from 0 to 30 included.

In [202]:
list(range(0, 31, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

## Use Conditional Statements and Loops Together

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [206]:
for a in range(1, 11):
    a *= 2
    print(a, end=" ")

2 4 6 8 10 12 14 16 18 20 

Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even".
Help yourself with the range() function to solve this exercise.

In [208]:
for x in range(1, 31):
    if x % 2 == 1:
        print(x, end=" ")
    else:
        print("Even", end=" ")

1 Even 3 Even 5 Even 7 Even 9 Even 11 Even 13 Even 15 Even 17 Even 19 Even 21 Even 23 Even 25 Even 27 Even 29 Even 

In [210]:
for y in range(1, 100):
    if y % 2 == 0:
        print(y, end=" ")
    else:
        print("Odd", end=" ")

Odd 2 Odd 4 Odd 6 Odd 8 Odd 10 Odd 12 Odd 14 Odd 16 Odd 18 Odd 20 Odd 22 Odd 24 Odd 26 Odd 28 Odd 30 Odd 32 Odd 34 Odd 36 Odd 38 Odd 40 Odd 42 Odd 44 Odd 46 Odd 48 Odd 50 Odd 52 Odd 54 Odd 56 Odd 58 Odd 60 Odd 62 Odd 64 Odd 66 Odd 68 Odd 70 Odd 72 Odd 74 Odd 76 Odd 78 Odd 80 Odd 82 Odd 84 Odd 86 Odd 88 Odd 90 Odd 92 Odd 94 Odd 96 Odd 98 Odd 

You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10.
Find two solutions of this problem.

In [211]:
n = [1,2,3,4,5,6]

In [212]:
for num in n:
    num *= 10
    print(num, end=" ")

10 20 30 40 50 60 

In [218]:
for num in range(len(n)):
    print(n[num] * 10, end=" ")

10 20 30 40 50 60 

In [224]:
nums = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

for n in nums:
    print(n ** 2, end=" ")

100 400 900 1600 2500 3600 4900 6400 8100 10000 

## All in - Conditional Statements, Functions, and Loops

You are provided with the 'nums' list. Complete the code in the cell that follows. Use a while loop to count the number of values lower than 20. 
*Hint: This exercise is similar to what we did in the video lecture. You might prefer using the x[item] structure for indicating the value of an element from the list.*

In [242]:
n = [1,12,24,31,51,70,100]

In [236]:
def count(nums):
    nums = sorted(nums)
    total = 0
    
    while nums[total] < 20:
        total += 1
    return total
    
print(f"Number of values less than 20: {count(n)}")
        


Number of values less than 20: 2


In [244]:
def count_values(nums):
    total = 0
    for n in nums:
        if n < 20:
            total += 1
    return total

print(count_values(n))

2


## Iterating over Dictionaries

In this exercise you will use the same dictionaries as the ones we used in the lesson - "prices" and "quantity". This time, don't just calculate all the money Jan spent. Calculate how much she spent on products with a price of 5 dollars or more.

In [238]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [239]:
for value in quantity:
    if prices[value] >= 5:
        money_spent += prices[value] * quantity[value]
    else:
        money_spent = money_spent
        
print(money_spent)

50


And how much did Jan spent on products that cost less than 5 dollars?

In [246]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [241]:
for v in quantity:
    if prices[v] < 5:
        money_spent += prices[v] * quantity[v]
    else:
        money_spent = money_spent
        
print(money_spent)

24


In [247]:
# how much did she spent in the supermarket?

for x in prices:
    money_spent = money_spent + (prices[x] * quantity[x])
    
print(money_spent)

74


In [254]:
prices = {
    "iPad": 600,
    "MacBook Pro": 1500,
    "iPhone": 1000,
    "AirPods": 200
}

quantity = {
     "iPad": 2,
    "MacBook Pro": 1,
    "iPhone": 3,
    "AirPods": 3
}

spent_at_store = 0

# of those, which products cost less than 1000?

# for v in quantity:
#     if prices[v] <= 1000:
#         spent_at_store += prices[v] * quantity[v]
#     else:
#         spent_at_store = spent_at_store
        
# print(spent_at_store)


In [255]:

# for value in prices:
#     spent_at_store = spent_at_store + (prices[value] * quantity[value])
    
# print(spent_at_store)

In [256]:
from math import sqrt

sqrt(25)

5.0

In [257]:
from math import sqrt as s 

s(30)

5.477225575051661

In [260]:
from math import *

sqrt(64)

8.0

In [262]:
import math
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



In [263]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.8/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
    

In [265]:
ceil(99.8)

100

In [266]:
round(120.89)

121

In [6]:
import numpy as np

np.__version__

'1.21.0'

In [1]:
import pandas as pd

pd.__version__

'1.3.0'

In [2]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
list2 = [6,7,8,9,10]
list2

[6, 7, 8, 9, 10]

In [4]:
list1.extend(list2)

In [5]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
# scalars
s = 5
s

5

In [9]:
v = np.array([5, -2, 9])
v

array([ 5, -2,  9])

In [11]:
m = np.array([[5, 12, 6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [12]:
m[0]

array([ 5, 12,  6])

In [13]:
m[1]

array([-3,  0, 14])

In [14]:
m[0][1]

12

In [15]:
m[1][2]

14

In [16]:
m[1][2] = 15

In [17]:
m

array([[ 5, 12,  6],
       [-3,  0, 15]])

In [18]:
# data types

type(s)

int

In [19]:
type(v)

numpy.ndarray

In [20]:
type(m)

numpy.ndarray

In [21]:
s_array = np.array(5)
s_array

array(5)

In [22]:
type(s_array)

numpy.ndarray

In [23]:
# data shapes
m.shape

(2, 3)

In [24]:
v.shape

(3,)

In [26]:
v.reshape(1, 3)

array([[ 5, -2,  9]])

In [28]:
# creating a tensor

m1 = np.array([[0,1,2], [3,4,5]])
m2 = np.array([[6,7,8], [9,10,11]])

print(m1, m2)


[[0 1 2]
 [3 4 5]] [[ 6  7  8]
 [ 9 10 11]]


In [29]:
t = np.array([m1, m2])
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [30]:
t.shape

(2, 2, 3)

In [33]:
# manually creating a tensor

t_manual = np.array([[[3, -1, 4], [9,8,7]], [[1, 3, -5], [-3, 0, 14]]])
t_manual

array([[[ 3, -1,  4],
        [ 9,  8,  7]],

       [[ 1,  3, -5],
        [-3,  0, 14]]])

In [34]:
t_manual.shape

(2, 2, 3)

In [35]:
m3 = np.array([[5,12,6], [-3,0,14]])
m4 = np.array([[9,8,7], [1,3,-5]])

m3 + m4

array([[14, 20, 13],
       [-2,  3,  9]])

In [36]:
type(m3)

numpy.ndarray

In [37]:
type(m4)

numpy.ndarray

In [38]:
m5 = np.array([[5, 3], [-2,4]])
m6 = np.array([[7, -5], [3,8]])

m5 - m6


array([[-2,  8],
       [-5, -4]])

In [43]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

v1 + v2

array([6, 6, 6, 6, 6])

In [44]:
v1 * v2

array([5, 8, 9, 8, 5])

In [45]:
v1 + 1

array([2, 3, 4, 5, 6])

In [46]:
v1 + 3

array([4, 5, 6, 7, 8])

In [48]:
x = np.array([1,2,3])
x1 = np.array([4,5,6])

x2 = x + x1

x2.T

array([5, 7, 9])

In [49]:
x.T

array([1, 2, 3])

In [60]:
size = [693, 656, 1060, 487, 1275, 456, 878, 234]

for i in range(len(size)):
    print(10190 + 223 * size[i])

164729
156478
246570
118791
294515
111878
205984
62372


In [53]:
a1 = np.array([[1, 693], [1, 656], [1, 1060], [1, 487], [1, 1275]])
a1

array([[   1,  693],
       [   1,  656],
       [   1, 1060],
       [   1,  487],
       [   1, 1275]])

In [61]:
a2 = np.array([[10190, 
                223]])
a2

array([[10190,   223]])

In [58]:
np.dot(a1, a2)

ValueError: shapes (5,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)